### ISSUE TITLE
How to Install?

### ISSUE THREAD

**Issue by DDVDKiller** [FiddyFive/DoLCM#1]
I'm having some trouble actually locating the cheat menu.

**Comment by FiddyFive** [comment]
You need to have a userscript extension installed in your browser. Personally, I use [Tampermonkey](https://www.tampermonkey.net/) but I hear Greasemonkey is also popular. Once you install that, you can add DoLCM.js as a script and when you load up the game, pressing `` ` `` should open the menu.

**Comment by DDVDKiller** [comment]
Thank you!
